title: Sherie Lin
profile: /assets/img/profile.png
description: Hi, my name is Sherie and I am student of Columbia... Data Scientist
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
